[package]
name = "cryptomator"
version = "0.0.0"
authors = ["Luc Street (@0xSiO)"]
description = "..."
repository = "https://github.com/0xSiO/cryptomator-rs"
license = "AGPL-3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.0"
jsonwebtoken = "8.1.0"
serde = { version = "1.0.0", features = ["derive"] }
uuid = { version = "1.1.0", features = ["serde", "v4"] }
