[package]
name = "cryptomator"
version = "0.0.0"
authors = ["Luc Street (@0xSiO)"]
description = "..."
repository = "https://github.com/0xSiO/cryptomator-rs"
license = "AGPL-3.0"
edition = "2021"

[dependencies]
aes-kw = { version = "0.2.0", features = ["std"] }
anyhow = "1.0.0"
base64ct = { version = "1.5.0", features = ["std"] }
jsonwebtoken = { version = "8.1.0", default-features = false }
scrypt = "0.10.0"
serde = { version = "1.0.0", features = ["derive"] }
uuid = { version = "1.1.0", features = ["serde", "v4"] }
