[package]
name = "cryptomator"
version = "0.0.0"
authors = ["Luc Street (@0xSiO)"]
description = "..."
repository = "https://github.com/0xSiO/cryptomator-rs"
license = "AGPL-3.0"
edition = "2021"

[dependencies]
